baseurl: http://www.joelbeckham.com/
name: Joel Beckham
title: Joel Beckham
description: Stuff I do
paginate: 5
Copyright: © 2016

params:
  description: this is my description
  cover: images/denali.jpg
  bio: my bio
#  googleAnalyticsUserID: UA-79101-12
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink: http://feeds.feedburner.com/... 
  githubName: joelbeckham
  twitterName: jbeckha2
  # facebookName: 
  # set true if you are not proud of using Hugo (true will hide the footer note Proudly published with HUGO.....)
  hideHUGOSupport: false